import {
  Bot,
  Code,
  Smartphone,
  Palette,
  Shield,
  BarChart,
  Cloud,
  Brush,
} from "lucide-react";

export const projects = [
  {
    id: "1",
    title: "Startup SaaS Dashboard",
    description: "Build a scalable SaaS dashboard with analytics and user management.",
    price: "$200/day",
    service: "Web Development",
    level: "Intermediate",
    duration: "3 months",
    location: "Remote",
    skills: ["React", "Node.js", "MongoDB"],
    image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c",
    user: {
      name: "David Johnson",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
  },
  {
    id: "2",
    title: "AI Customer Support Bot",
    description: "Develop an AI chatbot to automate customer support responses.",
    price: "$1200/month",
    service: "AI Automation",
    level: "Advanced",
    duration: "6 months",
    location: "Remote",
    skills: ["Python", "OpenAI API", "NLP"],
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995",
    user: {
      name: "Sarah Lee",
      avatar: "https://randomuser.me/api/portraits/women/45.jpg",
    },
  },
  {
    id: "3",
    title: "Fitness Mobile App",
    description: "Create a cross-platform fitness tracking app.",
    price: "$50/hour",
    service: "App Development",
    level: "Beginner",
    duration: "2 months",
    location: "Remote",
    skills: ["React Native", "Firebase"],
    image: "https://images.unsplash.com/photo-1526498460520-4c246339dccb",
    user: {
      name: "Michael Brown",
      avatar: "https://randomuser.me/api/portraits/men/11.jpg",
    },
  },
  {
    id: "4",
    title: "E-commerce Website Redesign",
    description: "Redesign UI/UX for a modern e-commerce platform.",
    price: "$300/day",
    service: "Web Design",
    level: "Intermediate",
    duration: "1 month",
    location: "Remote",
    skills: ["Figma", "UI/UX"],
    image: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8",
    user: {
      name: "Emily Clark",
      avatar: "https://randomuser.me/api/portraits/women/22.jpg",
    },
  },
  {
    id: "5",
    title: "Secure API Backend",
    description: "Develop a secure and scalable REST API system.",
    price: "$80/hour",
    service: "Cyber Security",
    level: "Advanced",
    duration: "4 months",
    location: "Remote",
    skills: ["Node.js", "JWT", "Security"],
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b",
    user: {
      name: "James Wilson",
      avatar: "https://randomuser.me/api/portraits/men/55.jpg",
    },
  },
  {
    id: "6",
    title: "Landing Page for Startup",
    description: "Design and build a high-converting landing page.",
    price: "$150/day",
    service: "Web Design",
    level: "Beginner",
    duration: "2 weeks",
    location: "Remote",
    skills: ["HTML", "CSS", "JavaScript"],
    image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
    user: {
      name: "Daniel Smith",
      avatar: "https://randomuser.me/api/portraits/men/41.jpg",
    },
  },
  {
    id: "7",
    title: "Data Analytics Dashboard",
    description: "Visualize business data with charts and reports.",
    price: "$900/month",
    service: "Data Analysis",
    level: "Intermediate",
    duration: "3 months",
    location: "Remote",
    skills: ["Python", "Pandas", "Chart.js"],
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71",
    user: {
      name: "Sophia Adams",
      avatar: "https://randomuser.me/api/portraits/women/33.jpg",
    },
  },
  {
    id: "8",
    title: "Cloud Infrastructure Setup",
    description: "Deploy scalable infrastructure using AWS.",
    price: "$100/hour",
    service: "DevOps and Cloud",
    level: "Advanced",
    duration: "2 months",
    location: "Remote",
    skills: ["AWS", "Docker", "CI/CD"],
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa",
    user: {
      name: "Chris Martin",
      avatar: "https://randomuser.me/api/portraits/men/67.jpg",
    },
  },
  {
    id: "9",
    title: "Brand Identity Design",
    description: "Create logo and branding for a startup.",
    price: "$500/project",
    service: "Graphic Design",
    level: "Beginner",
    duration: "3 weeks",
    location: "Remote",
    skills: ["Photoshop", "Illustrator"],
    image: "https://images.unsplash.com/photo-1609921212029-bb5a28e60960",
    user: {
      name: "Olivia White",
      avatar: "https://randomuser.me/api/portraits/women/12.jpg",
    },
  },
  {
    id: "10",
    title: "Social Media Automation Tool",
    description: "Automate posting and analytics for social media.",
    price: "$700/month",
    service: "AI Automation",
    level: "Intermediate",
    duration: "4 months",
    location: "Remote",
    skills: ["Node.js", "APIs"],
    image: "https://images.unsplash.com/photo-1611162616475-46b635cb6868",
    user: {
      name: "Ethan Carter",
      avatar: "https://randomuser.me/api/portraits/men/77.jpg",
    },
  },
  {
    id: "11",
    title: "Portfolio Website",
    description: "Build a modern personal portfolio website.",
    price: "$120/day",
    service: "Web Development",
    level: "Beginner",
    duration: "2 weeks",
    location: "Remote",
    skills: ["HTML", "CSS", "React"],
    image: "https://images.unsplash.com/photo-1467232004584-a241de8bcf5d",
    user: {
      name: "Grace Hall",
      avatar: "https://randomuser.me/api/portraits/women/60.jpg",
    },
  },
  {
    id: "12",
    title: "Crypto Trading Bot",
    description: "Develop an automated trading bot.",
    price: "$1500/month",
    service: "AI Automation",
    level: "Advanced",
    duration: "6 months",
    location: "Remote",
    skills: ["Python", "APIs"],
    image: "https://images.unsplash.com/photo-1621761191319-c6fb62004040",
    user: {
      name: "Ryan Scott",
      avatar: "https://randomuser.me/api/portraits/men/23.jpg",
    },
  },
  {
    id: "13",
    title: "Job Board Platform",
    description: "Build a platform for job listings and applications.",
    price: "$250/day",
    service: "Web Development",
    level: "Intermediate",
    duration: "3 months",
    location: "Remote",
    skills: ["React", "Express"],
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d",
    user: {
      name: "Nathan Young",
      avatar: "https://randomuser.me/api/portraits/men/29.jpg",
    },
  },
  {
    id: "14",
    title: "UI Kit Design System",
    description: "Create reusable UI components and design system.",
    price: "$800/project",
    service: "Web Design",
    level: "Intermediate",
    duration: "1 month",
    location: "Remote",
    skills: ["Figma", "Design Systems"],
    image: "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e",
    user: {
      name: "Isabella King",
      avatar: "https://randomuser.me/api/portraits/women/19.jpg",
    },
  },
  {
    id: "15",
    title: "Real-time Chat App",
    description: "Build a real-time messaging application.",
    price: "$90/hour",
    service: "App Development",
    level: "Intermediate",
    duration: "2 months",
    location: "Remote",
    skills: ["Socket.io", "React"],
    image: "https://images.unsplash.com/photo-1525182008055-f88b95ff7980",
    user: {
      name: "Liam Walker",
      avatar: "https://randomuser.me/api/portraits/men/88.jpg",
    },
  },
];


export const services = [
  {
    id: 1,
    name: "Web Development",
    icon: <Code size={48} color="#4B5563" />,
  },
  {
    id: 2,
    name: "AI Automation",
    icon: <Bot size={48} color="#4B5563" />,
  },
  {
    id: 3,
    name: "App Development",
    icon: <Smartphone size={48} color="#4B5563" />,
  },
  {
    id: 4,
    name: "Web Design",
    icon: <Palette size={48} color="#4B5563" />,
  },
  {
    id: 5,
    name: "Graphic Design",
    icon: <Brush size={48} color="#4B5563" />,
  },
  {
    id: 6,
    name: "Cyber Security",
    icon: <Shield size={48} color="#4B5563" />,
  },
  {
    id: 7,
    name: "Data Analysis",
    icon: <BarChart size={48} color="#4B5563" />,
  },
  {
    id: 8,
    name: "DevOps & Cloud",
    icon: <Cloud size={48} color="#4B5563" />,
  },
];

